version: '3'
services:
  postgres:
    image: postgres:14-alpine3.15
    restart: unless-stopped
    volumes:
      - postgresdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: names
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
  name-wall:
    build:
      context: ./name-wall
      dockerfile: Dockerfile
    restart: unless-stopped
    healthcheck:
      test: wget -nv --tries=1 --spider http://127.0.0.1:5000 || exit 1
      interval: 30s
      timeout: 5s
      retries: 2
    depends_on:
      - postgres
  nginx: 
    image: nginx:stable
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 8080:80
    depends_on:
      - postgres
      - name-wall

volumes:
  postgresdata: